---
title: "Practical Report 9"
output:
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    highlight: monochrome
  bookdown::gitbook:
    highlight: monochrome
    code_folding: hide
    global_numbering: yes
  html_document:
    df_print: paged
    code_folding: hide
fontsize: 12pt
---

```{r setup, include = FALSE}
require(knitr)
pdf_doc <- knitr::is_latex_output()
if (pdf_doc) {opts_chunk$set(echo=FALSE, fig.align="center", out.width="60%", comment="")} else {opts_chunk$set(comment="")}
```

# Effectiveness of blood pressure treatment

```{r, LoadData}
bpdata <- read.csv("bpdata.csv")
lm.out1 <- lm(BPchange ~ BPinit + Dose, data=bpdata)
```

## Part a

<!--- Perform a test for the existence of regression --->

```{r, GlobalFtest}
    # Fit null model
    lm.out0 <- lm(BPchange ~ 1, data=bpdata)
    # Use the anova function with two arguments
    anova(lm.out0, lm.out1)
```

<!--- Identify the entries needed to compile the corresponding ANOVA table-->

## Part b

<!--- Perform a sequential ANOVA --->

```{r, SequentialAnova}

```

## Part c

<!--- Controlling for initial blood pressure, does the new drug have an effect on blood pressure? --->

## Part d

<!--- How can the results of the sequential ANOVA be used to re-produce the results for the ANOVA for a test of existence in a? --->


# Model selection statistics

<!--- Experiment 1 --->
```{r,  fig.cap=""}
# Generate data
set.seed(22)
x <- matrix(rnorm(5000),100,50)
y <- rnorm(100)
data <- as.data.frame(cbind(y,x))
# 
r2 <- rep(NA,50)
for (j in 1:50){
  data_temp<-data[ ,1:(j+1)]
  r2[j] <- summary(lm(y ~ ., data=data_temp))$r.squared 
}
# Plot the sequence of R^2 statistics
plot(r2,type="l",lwd=1.5,col="blue",
     xlab="number of predictor variables",ylab=expression(R^2))
points(r2,col="blue",pch=20)
```

<!--- Experiment 2 -->

```{r, fig.cap=""}
# Generate data
set.seed(13)
x <- matrix(rnorm(1000),100,10)
y <- rnorm(100) + 1 + 0.25*x[,1] + 0.5*x[,2] + 0.5*x[,3] 
data <- as.data.frame(cbind(y,x))
#
r2 <- rep(NA,10)
r2adj <- rep(NA,10)
for (j in 1:10){
data_temp<-data[,1:(j+1)]
r2[j] <- summary(lm(y ~ ., data=data_temp))$r.squared 
r2adj[j] <- summary(lm(y ~ ., data=data_temp))$adj.r.squared 
}
# Adjust margins of plotting region
par(mar=c(5,6,1,1)+.1)
# Plot sequence of R^2 and adjusted R^2. 
plot(2:10, r2[2:10],type="l",lwd=2,lty=3,col="blue",
     xlab="number of predictor variables",ylab=expression(R^2*", "*R[adj]^2),
     ylim=c(min(r2adj[2:10]),max(r2)), cex.lab=1.5, xaxp=c(2,10,8))
# Add points to illustrate values taken by R^2 and adjusted R^2. 
points(2:10,r2adj[2:10],type="l",lwd=1.5,col="darkred")
points(2:10,r2[2:10],col="blue",pch=20, cex=1.5)
points(2:10,r2adj[2:10],col="darkred",pch=20, cex=1.5)
# Add legend
legend("bottomright", c(expression(R^2), expression(R[adj]^2)), 
       col = c("blue","darkred"), lty = c(3, 1), pch=c(20,20),cex=1.3, lwd=2)
# Separate truly informative predictors from non-informative predictors
abline(v=3)
abline(h=r2adj[3],col="gray50",lty=2)
```




