---
title: "Practical Report 1"
output: pdf_document
fontsize: 12pt
---

```{r setup, include = FALSE}
require(knitr)
pdf_doc <- knitr::is_latex_output()
if (pdf_doc) {opts_chunk$set(echo=FALSE, fig.dim = c(4.5, 4), fig.align="center")}

# install.packages("readr")
library(readr)
```

# Coursework and exam performance

## Question 1

```{r DataInput, echo=FALSE}
# Data
Exam <- read_csv("../data/Exam.csv", show_col_types = FALSE)
print(head(Exam))
print(is.na(Exam))
```

```{r DataVisual, echo=FALSE}
print(summary(Exam))
hist(Exam$cw)
hist(Exam$ex)
```

## Question 2 and 3

```{r Scatterplot, fig.cap=""}
plot(ex ~ cw, xlab="Coursework mark (out of 20)", 
      ylab="Exam mark (out of 100)",
      xlim=c(0,20), ylim=c(35,100), col="navy", pch=16, data=Exam)
```

```{r Scatterplot and fit, fig.cap=""}
# Add code here to produce a scatterplot of the data
plot(ex ~ cw, xlab="Coursework mark (out of 20)", 
      ylab="Exam mark (out of 100)",
      xlim=c(0,20), ylim=c(35,100), col="navy", pch=16, data=Exam)

# Fit a linear model of ex on cw
model1 <- lm(ex ~ cw, data=Exam)

# Add the fitted regression line to the plot
abline(model1, col="gray20")
```

## Question 4

```{r}
coef(model1)
```

## Question 5

```{r}
predict(model1, newdata = list(cw = 10))
```

## Question 6

```{r}
lowest_mark <- as.numeric((40-coef(model1)[1]) / coef(model1)[2])
print(lowest_mark)
```

```{r}
predict(model1, newdata = list(cw = lowest_mark))
```

## Question 7

```{r}
predict(model1, newdata = list(cw = 20))
```

## Question 8 and 9

```{r}
Exam$cwp <- 5*Exam$cw
model2 <- lm(ex ~ cwp, data=Exam)
coef(model2)
```

```{r Reparameterisation, out.width="49%", fig.show="hold", fig.cap=""}
# Scatterplot illustrating original parameterisation
plot(ex ~ cw, xlab="Coursework mark (out of 20)", ylab="Exam mark (out of 100)",
     xlim=c(0,20), ylim=c(35,100), col="navy", pch=16, data=Exam)
abline(model1, col="gray20")
exam1.fit <- fitted(model1)
points(exam1.fit ~ cw, col="darkred", pch=18, data=Exam)
legend("bottomright", c("observed response", "fitted values for model 1"),
       pch=c(16, 18), col=c("navy", "darkred"))


# Scatterplot illustrating new parameterisation
plot(ex ~ cwp, xlab="Coursework mark (out of 100)", ylab="Exam mark (out of 100)",
     xlim=c(0,100), ylim=c(35,100), col="navy", pch=16, data=Exam)
abline(model2)
exam2.fit <- fitted(model2)
points(exam2.fit ~ cwp, col="darkred", pch=18, data=Exam)
legend("bottomright", c("observed response", "fitted values for model 2"), 
       pch=c(16, 18), col=c("navy", "darkred"))
```

## Question 10

```{r}
print("Model 1:")
print(coef(model1))

print("Model 2:")
print(coef(model2))
```
